### ISSUE TITLE
ValueError: Cannot import git (pip install GitPython).

### ISSUE THREAD

**Issue by UNdeng** [nttcslab-sp/dnn_wpe#2]
I run the "python train.py", and get an error,
ValueError: Cannot import git (pip install GitPython).
Either GitPython or the git executable is missing.
You can disable git with:
sacred.Experiment(..., save_git_info=False)

**Comment by Re-dot-art** [comment]
> 

Hello, have you solved the above problem? How did you solve it?

**Comment by qidong1** [comment]
> I run the "python train.py", and get an error, ValueError: Cannot import git (pip install GitPython). Either GitPython or the git executable is missing. You can disable git with: sacred.Experiment(..., save_git_info=False)

Hello, have you solved the above problem? How did you solve it?

**Comment by abdullahiisaahmed** [comment]
Hi, were you able to resolve this error? If yes, could you please share how you did it? Thanks

**Update:** 
I was working on an HPC and I realized that I hadn't loaded the Git module. So, if you're still facing a similar issue, you can check the available modules using `module avail git`. Then, load the appropriate git module with `module load git/x.xx.x-GCCcore-x.x.x-nodocs`. This perfectly resolved my problem.
