### ISSUE TITLE
./prepare_REVERB_data.sh <wsjcam0> <REVERB_DATA_OFFICIAL>

### ISSUE THREAD

**Issue by UNdeng** [nttcslab-sp/dnn_wpe#3]
hello sir,
I want to how to run this command, "./prepare_REVERB_data.sh <wsjcam0> <REVERB_DATA_OFFICIAL>" , 
it always fails with error : bash: syntax error near unexpected token `<', and if I change it to  ./prepare_REVERB_data.sh \<wsjcam0\> \<\REVERB_DATA_OFFICIAL\>, it shows "Please install sox.", but I am sure I have installed the sox in Linux and python

**Comment by jieyangzhang** [comment]
Maybe you need to Download <REVERB_DATA_OFFICIAL> & <wsjcam0>...........

**Comment by josanna** [comment]
> Maybe you need to Download <REVERB_DATA_OFFICIAL> & ...........

 I will thank you very much if you wish share  <wsjcam0> <\REVERB_DATA_OFFICIAL>for free

**Comment by jieyangzhang** [comment]
> 

In fact, I don't have the extra money to get this data set. It's too sad

**Comment by UNdeng** [comment]
I turn to nara-WPE
